# Generated by Django 2.2.1 on 2019-05-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePaymentMethod',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('value', models.IntegerField(db_column='nb_value')),
                ('meansPayment', models.ForeignKey(db_column='id_means_payment', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.MeansPayment')),
                ('sale', models.ForeignKey(db_column='id_sale', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Sale')),
            ],
            options={
                'db_table': 'sale_means_payment',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='salepaymentmethod',
            index=models.Index(fields=['sale'], name='sale_means__id_sale_aac3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='salepaymentmethod',
            index=models.Index(fields=['meansPayment'], name='sale_means__id_mean_460f10_idx'),
        ),
    ]
