# Generated by Django 2.2.1 on 2019-05-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190515_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepaymentmethod',
            name='value',
            field=models.DecimalField(db_column='nb_value', decimal_places=4, max_digits=16),
        ),
    ]
