# Generated by Django 2.2.1 on 2019-05-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190515_1931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalePaymentMethod',
            new_name='MeansPaymentSale',
        ),
        migrations.RemoveIndex(
            model_name='meanspaymentsale',
            name='sale_means__id_sale_aac3c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='meanspaymentsale',
            name='sale_means__id_mean_460f10_idx',
        ),
        migrations.AddIndex(
            model_name='meanspaymentsale',
            index=models.Index(fields=['sale'], name='means_payme_id_sale_59bc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='meanspaymentsale',
            index=models.Index(fields=['meansPayment'], name='means_payme_id_mean_b0e46f_idx'),
        ),
        migrations.AlterModelTable(
            name='meanspaymentsale',
            table='means_payment_sale',
        ),
    ]
