# Generated by Django 2.2.1 on 2019-05-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190515_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(db_column='nb_subtotal', decimal_places=3, max_digits=10, null=True),
        ),
    ]
