# Generated by Django 2.2.1 on 2019-05-21 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_saleitem_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('date', models.DateTimeField(db_column='dt_sale', default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('T', 'Transferência')], db_column='tx_type', default='E', max_length=1)),
                ('document', models.CharField(db_column='tx_document', max_length=256, null=True)),
            ],
            options={
                'db_table': 'movement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockAddress',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('description', models.CharField(db_column='tx_description', max_length=104)),
            ],
            options={
                'db_table': 'stock_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True)),
                ('quantity', models.IntegerField(db_column='nb_quantity', default=0)),
                ('movement', models.ForeignKey(db_column='id_movement', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Movement')),
                ('product', models.ForeignKey(db_column='id_product', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Product')),
            ],
            options={
                'db_table': 'movement_item',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='movement',
            name='address',
            field=models.ForeignKey(db_column='id_address', db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.StockAddress'),
        ),
        migrations.AddIndex(
            model_name='movementitem',
            index=models.Index(fields=['movement'], name='movement_it_id_move_c24379_idx'),
        ),
        migrations.AddIndex(
            model_name='movementitem',
            index=models.Index(fields=['product'], name='movement_it_id_prod_fb3767_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['address'], name='movement_id_addr_b48755_idx'),
        ),
    ]
