# Generated by Django 2.2.1 on 2019-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190521_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementitem',
            name='quantity',
            field=models.DecimalField(db_column='nb_quantity', decimal_places=3, max_digits=10),
        ),
    ]
